// <auto-generated />
using LikeslMission6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LikeslMission6.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230223045344_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("LikeslMission6.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Romance"
                        });
                });

            modelBuilder.Entity("LikeslMission6.Models.MovieResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectorName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            DirectorName = "Tyler Nilson",
                            Edited = false,
                            MovieName = "The Peanut Butter Falcon",
                            Notes = "Best Movie EVER!",
                            Rating = "PG",
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            DirectorName = "Gilbert Wong",
                            Edited = true,
                            LentTo = "Abby Jensen",
                            MovieName = "10 Things I Hate About You",
                            Rating = "PG-13",
                            Year = 1999
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DirectorName = "Joseph Kosinski",
                            Edited = false,
                            MovieName = "Top Gun: Maverick",
                            Notes = "A thrill!!",
                            Rating = "PG-13",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("LikeslMission6.Models.MovieResponse", b =>
                {
                    b.HasOne("LikeslMission6.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
