// <auto-generated />
using LikeslMission6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LikeslMission6.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20230214050045_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("LikeslMission6.Models.MovieResponse", b =>
                {
                    b.Property<int>("ApplicatioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicatioId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicatioId = 1,
                            Category = "Adventure/Drama",
                            DirectorName = "Tyler Nilson",
                            Edited = false,
                            MovieName = "The Peanut Butter Falcon",
                            Notes = "Best Movie EVER!",
                            Rating = "PG",
                            Year = 2019
                        },
                        new
                        {
                            ApplicatioId = 2,
                            Category = "Romance/Comedy",
                            DirectorName = "Gilbert Wong",
                            Edited = true,
                            LentTo = "Abby Jensen",
                            MovieName = "10 Things I Hate About You",
                            Rating = "PG-13",
                            Year = 1999
                        },
                        new
                        {
                            ApplicatioId = 3,
                            Category = "Action/Adventure",
                            DirectorName = "Joseph Kosinski",
                            Edited = false,
                            MovieName = "Top Gun: Maverick",
                            Notes = "A thrill!!",
                            Rating = "PG-13",
                            Year = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
